Additional data visualizations (#7)
* - Support for returning the "hovered item" on all levels (not only on Component level)
- Data visualization for Bezier4x3, Bounds3 and Segment

* Data visualization for
- float3
- PathElement (buffer)
- NavigationLanes (buffer)

+ Hovered object fixes

* Fix of sporadic exception:
                    NullReferenceException: Object reference not set to an instance of an object
                      at Unity.Collections.LowLevel.Unsafe.UnsafeUtility.ReadArrayElement[T] (System.Void* source, System.Int32 index) [0x00000] in <b4e80bd296bc48ba89d931486f299d70>:0
                      at Unity.Collections.NativeArray`1+Enumerator[T].MoveNext () [0x00027] in <b4e80bd296bc48ba89d931486f299d70>:0
                      at SceneExplorer.System.InspectObjectToolSystem.RenderPathElements (Unity.Entities.Entity entityWithPathElements, Game.Rendering.OverlayRenderSystem+Buffer buffer) [0x0004a] in C:\Users\gabor\Source\Repos\SceneExplorer\SceneExplorer\System\InspectObjectToolSystem.cs:621

* Not needed usings were removed.

* Support for rendering only the RouteSegments between the transit line waypoints. Duplicate rendering of the transit line was also eliminated.

* Bumped the version number to 0.2.10 and added ChangeLog.

* - Using GizmoBatcher instead of OverlayRenderer
- Inifinite loop bug was fixed in PathElement rendering
- Warning was removed because it was logged too many times (despite that the visualization looked ok)

* Path rendering performance optimizations:
- The whole rendering is moved out of the main thread into a job
- Burts compilation was enabled for the PathRenderingJob
- Bezier rendering segment count was limited to 6 (instead of 16)

* Review finding fixes

* Fix of wrong dependency variable (at this point inputDeps might contain already more dependencies than Dependency)